Resources:
  EC2Instance:
  Type: "AWS::EC2::Instance"
  Properties:
    ImageID: ami-1234567
    InstanceType: t2.micro

# With !Ref, you will only get access to EC2 ID
DbSubnet1:
  Type: "AWS::EC2::Subnet"
  Properties:
    EC2ID: !Ref EC2Instance

# Whereas !Ref, allows you get specific attributes from
# the EC2 instance
NewVolume:
  Type: "AWS::EC2::Volume"
  Properties:
    Size: 100
    AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
